CREATE TYPE "public"."attendance_status" AS ENUM('normal', 'late', 'early_leave', 'absent');--> statement-breakpoint
CREATE TYPE "public"."language" AS ENUM('ko', 'en');--> statement-breakpoint
CREATE TYPE "public"."theme" AS ENUM('light', 'dark', 'system');--> statement-breakpoint
CREATE TYPE "public"."user_role" AS ENUM('user', 'admin');--> statement-breakpoint
CREATE TABLE "clock-in_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "clock-in_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "clock-in_attendance_record" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "clock-in_attendance_record_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"workplaceId" integer NOT NULL,
	"date" date NOT NULL,
	"clockInTime" timestamp with time zone,
	"clockOutTime" timestamp with time zone,
	"clockInLocation" json,
	"clockOutLocation" json,
	"status" "attendance_status" DEFAULT 'normal' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "clock-in_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "clock-in_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "clock-in_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "clock-in_user_setting" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "clock-in_user_setting_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"defaultClockInTime" time DEFAULT '09:00:00' NOT NULL,
	"defaultClockOutTime" time DEFAULT '18:00:00' NOT NULL,
	"language" "language" DEFAULT 'ko' NOT NULL,
	"theme" "theme" DEFAULT 'system' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "clock-in_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255),
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255),
	"user" "user_role" DEFAULT 'user' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "clock-in_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "clock-in_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
CREATE TABLE "clock-in_workplace" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "clock-in_workplace_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"latitude" numeric(10, 8) NOT NULL,
	"longitude" numeric(11, 8) NOT NULL,
	"radius" integer DEFAULT 100 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "clock-in_account" ADD CONSTRAINT "clock-in_account_userId_clock-in_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."clock-in_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "clock-in_attendance_record" ADD CONSTRAINT "clock-in_attendance_record_userId_clock-in_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."clock-in_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "clock-in_attendance_record" ADD CONSTRAINT "clock-in_attendance_record_workplaceId_clock-in_workplace_id_fk" FOREIGN KEY ("workplaceId") REFERENCES "public"."clock-in_workplace"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "clock-in_post" ADD CONSTRAINT "clock-in_post_createdById_clock-in_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."clock-in_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "clock-in_session" ADD CONSTRAINT "clock-in_session_userId_clock-in_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."clock-in_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "clock-in_user_setting" ADD CONSTRAINT "clock-in_user_setting_userId_clock-in_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."clock-in_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "clock-in_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "clock-in_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "clock-in_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "clock-in_session" USING btree ("userId");