CREATE TYPE "public"."holiday_type" AS ENUM('weekly', 'specific_date');--> statement-breakpoint
CREATE TABLE "clock-in_holiday" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "clock-in_holiday_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"type" "holiday_type" NOT NULL,
	"weeklyDay" integer,
	"specificDate" date,
	"description" text,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
